#!/bin/sh

ver=`git rev-parse --verify --short HEAD`
if ! (($?)); then

	printf "%s%s" "-g" "$ver"
	if git diff-index --name-only HEAD > /dev/null; then
		printf "%s" "-dirty"
	fi

else
	printf "-nover"
fi
