SOURCE += $(PROG)/auton.c   \
          $(PROG)/encoder.c \
          $(PROG)/robot.c   \
          $(PROG)/user.c    \
		  $(PROG)/state.c   \

HEADERS += $(PROG)/auton.h   \
           $(PROG)/encoder.h \
           $(PROG)/ports.h   \
           $(PROG)/robot.h   \
           $(PROG)/user.h    \
           $(PROG)/util.h    \
           $(PROG)/state.h
