include $(ARCH)/mcc18.mk

ARCHEXT = hex

CSOURCE += $(ARCH)/hax.c  \
	   $(ARCH)/crt0.c \
	   $(ARCH)/ifi_lib.c  

ASOURCE += $(ARCH)/ifi_util.asm

HEADERS += $(ARCH)/master.h \
	   $(ARCH)/ifi_lib.h

