SOURCE  += $(ARCH)/hax.c          \
           $(ARCH)/rcc.c          \
           $(ARCH)/spi.c          \
           $(ARCH)/stm32f10x_it.c \
           $(ARCH)/syscall.c      \
           $(ARCH)/usart.c

include $(ARCH)/gcc.mk
