CSOURCE += $(PROG)/auton.c   \
           $(PROG)/encoder.c \
           $(PROG)/robot.c   \
           $(PROG)/user.c

HEADERS += $(PROG)/auton.h   \
           $(PROG)/encoder.h \
           $(PROG)/ports.h   \
           $(PROG)/robot.h   \
           $(PROG)/user.h    \
           $(PROG)/util.h
